# Generated by Django 5.2.7 on 2025-10-07 02:10

import shortuuid.main
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0003_chatgroup_is_private_chatgroup_members_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='users_online',
            field=models.ManyToManyField(blank=True, default=shortuuid.main.ShortUUID.uuid, related_name='users_online', to=settings.AUTH_USER_MODEL),
        ),
    ]
