# Generated by Django 5.2.7 on 2025-10-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0009_alter_chatgroup_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default='hmYhKXsjk7Sevd7d5sFzmw', max_length=100, unique=True),
        ),
    ]
