# Generated by Django 5.2.7 on 2025-10-09 11:30

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0021_groupmessage_files_alter_chatgroup_group_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='files',
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=100, unique=True),
        ),
    ]
